services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.1-ubi8
    environment:
      MONGO_INITDB_DATABASE: photoalbum
#    volumes:
#      - ./db/migration:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: pg_isready -U tom -d photoalbum
#      interval: 10s
#      retries: 10
    expose:
      - "27017"
  photoalbum:
    image: photoalbum:0.0.5-SNAPSHOT
    environment:
      DB_HOST: mongodb
    ports:
      - 8090:8080
#    depends_on:
#      postgres:
#        condition: service_healthy
