apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoalbum-deployment
  labels:
    app: photoalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoalbum
  template:
    metadata:
      labels:
        app: photoalbum
    spec:
      volumes:
      - name: photoalbum-pv-storage
        persistentVolumeClaim:
          claimName: pictures-pv-claim
      containers:
      - name: photoalbum
        image: tomgrund/photoalbum:0.0.6-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef: 
              name: mongo-config
              key: mongo-url
        volumeMounts:
          - mountPath: "/mnt/data"
            name: photoalbum-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: photoalbum-service
spec:
  type: NodePort
  selector:
    app: photoalbum
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100

# http://192.168.49.2:30100/swagger-ui/index.html