apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoalbum-deployment
  labels:
    app: photoalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoalbum
  template:
    metadata:
      labels:
        app: photoalbum
    spec:
      containers:
      - name: photoalbum
        image: tomgrund/photoalbum:0.0.5-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        # - name: USER_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-user
        # - name: USER_PWD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef: 
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: photoalbum-service
spec:
  type: NodePort
  selector:
    app: photoalbum
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100

# http://192.168.49.2:30100/swagger-ui/index.html