apiVersion: v1
kind: PersistentVolume
metadata:
  name: pictures-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/Bilder"

# VORHER: minikube mount <Verzeichnis mit Bildern>:/data/Bilder
